# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-23 08:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 23, 8, 12, 26, 515847)),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 23, 8, 12, 26, 515864)),
        ),
    ]
