# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-30 08:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20171023_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 30, 8, 45, 4, 688520)),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 30, 8, 45, 4, 688538)),
        ),
    ]
