# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-23 08:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catName', models.CharField(max_length=128, unique=True)),
                ('catSlug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proName', models.CharField(max_length=128, unique=True)),
                ('proSlug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='images/products')),
                ('description', models.CharField(max_length=128)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField(default=1)),
                ('availability', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=datetime.datetime(2017, 10, 23, 8, 11, 6, 40162))),
                ('updated', models.DateTimeField(default=datetime.datetime(2017, 10, 23, 8, 11, 6, 40178))),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Category')),
            ],
        ),
    ]
